import '../models/student.dart';
import '../models/attendance_record.dart';

class FapService {
  /// Parse FAP HTML hoặc text danh sách sinh viên
  static List<Student> parseStudentList(String input, String className) {
    final List<Student> students = [];
    final lines = input.split(RegExp(r'[\r\n]+'));

    // Regex tìm mã sinh viên FPT (ví dụ: SE170123, HE160111, IA150222, QE180001, SS190123...)
    final rollNumberRegex = RegExp(r'\b([A-Z]{2}\d{5,7})\b', caseSensitive: false);

    for (final line in lines) {
      final trimmed = line.trim();
      if (trimmed.isEmpty) continue;

      final match = rollNumberRegex.firstMatch(trimmed);
      if (match != null) {
        final rollNumber = match.group(1)!.toUpperCase();

        // Cố gắng tìm họ tên bằng cách loại bỏ mã số và các ký tự thừa
        String name = trimmed
            .replaceAll(rollNumber, '')
            .replaceAll(RegExp(r'^\d+[\s\.\-]+'), '') // Bỏ STT đầu dòng
            .replaceAll(RegExp(r'\s+'), ' ')
            .trim();

        if (name.isEmpty) {
          name = 'Sinh viên $rollNumber';
        }

        final email = '${name.split(' ').last.toLowerCase()}${rollNumber.toLowerCase()}@fpt.edu.vn';

        final nameWords = name.split(' ').where((w) => w.isNotEmpty).toList();
        String surname = '';
        String middleName = '';
        String givenName = '';

        if (nameWords.length >= 3) {
          surname = nameWords.first;
          givenName = nameWords.last;
          middleName = nameWords.sublist(1, nameWords.length - 1).join(' ');
        } else if (nameWords.length == 2) {
          surname = nameWords[0];
          givenName = nameWords[1];
        } else if (nameWords.length == 1) {
          givenName = nameWords[0];
        }

        if (!students.any((s) => s.member == rollNumber)) {
          students.add(
            Student(
              member: rollNumber,
              code: rollNumber,
              surname: surname,
              middleName: middleName,
              givenName: givenName,
              customFullName: name,
              email: email,
              className: className,
              totalSlots: 20,
              absentSlots: 0,
            ),
          );
        }
      }
    }

    return students;
  }

  /// Sinh đoạn mã JavaScript (FAP Auto-fill Bridge Script)
  /// Giảng viên / Người dùng chỉ cần dán đoạn mã này vào F12 Console của trang FAP hoặc bấm Bookmarklet
  /// là FAP sẽ tự động chọn trúng các radio button Present / Absent và highlight dòng!
  static String generateFapFillScript(List<AttendanceRecord> records) {
    final recordEntries = records
        .map((r) => "{ roll: '${r.rollNumber}', status: '${r.status.fapValue}', note: '${r.note}' }")
        .join(',\n    ');

    return '''
// === FAP ATTENDANCE AUTO-FILL SCRIPT (Generated by PRM Desktop App) ===
(function() {
  const attendanceData = [
    $recordEntries
  ];

  let filledCount = 0;
  let absentCount = 0;
  let presentCount = 0;

  console.log('[PRM Desktop] Bắt đầu tự động điền ' + attendanceData.length + ' sinh viên lên FAP...');

  // Tìm tất cả các dòng sinh viên trong bảng FAP
  const rows = document.querySelectorAll('table tr');
  
  attendanceData.forEach(item => {
    let found = false;

    rows.forEach(row => {
      const text = row.innerText || '';
      if (text.toUpperCase().includes(item.roll.toUpperCase())) {
        found = true;
        
        // Tìm radio buttons trong dòng này
        const radios = row.querySelectorAll('input[type="radio"]');
        radios.forEach(radio => {
          const parentText = (radio.parentElement ? radio.parentElement.innerText : '').toLowerCase();
          const radioVal = (radio.value || '').toLowerCase();
          const radioId = (radio.id || '').toLowerCase();

          const isPresentTarget = item.status.toLowerCase() === 'present';
          const isAbsentTarget = item.status.toLowerCase() === 'absent';

          if (isPresentTarget && (parentText.includes('present') || radioVal.includes('present') || radioId.includes('present') || radioVal === '1' || parentText.includes('có mặt'))) {
            radio.checked = true;
            radio.dispatchEvent(new Event('change', { bubbles: true }));
            radio.dispatchEvent(new Event('click', { bubbles: true }));
            row.style.backgroundColor = '#d1fae5'; // Xanh lá
            presentCount++;
          } else if (isAbsentTarget && (parentText.includes('absent') || radioVal.includes('absent') || radioId.includes('absent') || radioVal === '0' || parentText.includes('vắng'))) {
            radio.checked = true;
            radio.dispatchEvent(new Event('change', { bubbles: true }));
            radio.dispatchEvent(new Event('click', { bubbles: true }));
            row.style.backgroundColor = '#fee2e2'; // Đỏ nhạt
            absentCount++;
          }
        });

        // Điền ghi chú nếu có
        if (item.note && item.note.trim() !== '') {
          const noteInput = row.querySelector('input[type="text"], textarea');
          if (noteInput) {
            noteInput.value = item.note;
            noteInput.dispatchEvent(new Event('input', { bubbles: true }));
          }
        }

        filledCount++;
      }
    });
  });

  // Hiển thị thông báo trên màn hình FAP
  const banner = document.createElement('div');
  banner.style.position = 'fixed';
  banner.style.top = '20px';
  banner.style.right = '20px';
  banner.style.backgroundColor = '#1e293b';
  banner.style.color = '#ffffff';
  banner.style.padding = '16px 24px';
  banner.style.borderRadius = '12px';
  banner.style.boxShadow = '0 10px 25px rgba(0,0,0,0.3)';
  banner.style.zIndex = '999999';
  banner.style.fontFamily = 'Segoe UI, sans-serif';
  banner.style.border = '2px solid #F36F21';
  banner.innerHTML = `
    <div style="font-weight:bold; font-size:16px; margin-bottom:6px; color:#F36F21;">⚡ PRM FAP Bridge: Đã tự động điền!</div>
    <div style="font-size:14px;">Tổng SV đã điền: <b>\${filledCount}</b> (Có mặt: <b style="color:#34d399">\${presentCount}</b>, Vắng: <b style="color:#f87171">\${absentCount}</b>)</div>
    <div style="font-size:12px; margin-top:6px; color:#94a3b8;">Vui lòng kiểm tra lại bảng màu và bấm nút Lưu trên FAP!</div>
  `;
  document.body.appendChild(banner);
  setTimeout(() => banner.remove(), 7000);

  alert('⚡ Đã hoàn tất tự động điền ' + filledCount + ' sinh viên lên FAP! Hãy kiểm tra và nhấn Save trên FAP.');
})();
''';
  }
}
